### ISSUE TITLE
Crash when wrong field number is taken

### ISSUE THREAD

**Issue by Kaligule** [robbiebarrat/unbeatable_tictactoe#1]
number that are not in range(-9,9) let the programm crash.

**Comment by robbiebarrat** [comment]
Fixed it.
Now it makes sure that the number the human enters is between zero and eight, and that it is an integer.

**Comment by Kaligule** [comment]
Thanks.
You could additionaly add a test weather the input is empty, so if nothing is entered you get a different message. This might help: http://stackoverflow.com/questions/7896495/python-how-to-check-if-a-line-is-an-empty-line

**Comment by robbiebarrat** [comment]
Hey -- thanks for the link -- it should work now. If you have any more suggestions on what I could do to make the program better I'd love to hear them.
